---
- name: Install Jenkins on Ubuntu 
  hosts: jenkins
  become: yes
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Java (Jenkins dependency)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] http://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

# Automates:
# sudo apt update
# sudo apt install openjdk-11-jdk -y
# wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
# sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
# sudo apt update
# sudo apt install jenkins -y
# sudo systemctl enable jenkins
# sudo systemctl start jenkins
