---
- name: Install Jenkins on Ubuntu
  hosts: jenkins
  become: yes
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Java (Jenkins dependency) (Java 17)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Jenkins repository key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins user has correct ownership of its directory
      file:
        path: /usr/share/jenkins
        owner: jenkins
        group: jenkins
        mode: '0755'
        state: directory

    - name: Download the latest Jenkins WAR file
      get_url:
        url: https://get.jenkins.io/war-stable/latest/jenkins.war
        dest: /usr/share/jenkins/jenkins.war
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Modify Jenkins systemd service file
      copy:
        dest: /lib/systemd/system/jenkins.service
        content: |
          [Unit]
          Description=Jenkins Continuous Integration Server
          After=network.target

          [Service]
          Type=simple
          User=jenkins
          ExecStart=/usr/bin/java -jar /usr/share/jenkins/jenkins.war --httpPort=8080
          Restart=on-failure
          SuccessExitStatus=143

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Restart Jenkins

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Restart Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: restarted

# Automates:
# # 1. Update APT package list
# sudo apt update -y

# # 2. Install Java 17 (Required for Jenkins)
# sudo apt install -y openjdk-17-jdk

# # 3. Download and add Jenkins GPG key
# curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

# # 4. Add Jenkins repository
# echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

# # 5. Update APT package list again (to recognize the new Jenkins repo)
# sudo apt update -y

# # 6. Install Jenkins
# sudo apt install -y jenkins

# # 7. Ensure Jenkins user owns its home directory (fixes permission issues)
# sudo chown -R jenkins:jenkins /var/lib/jenkins

# # 8. Download the latest Jenkins WAR file (Ensures the latest stable version)
# sudo wget -O /usr/share/jenkins/jenkins.war https://get.jenkins.io/war-stable/latest/jenkins.war
# sudo chown jenkins:jenkins /usr/share/jenkins/jenkins.war
# sudo chmod 755 /usr/share/jenkins/jenkins.war

# # 9. Reload systemd to apply Jenkins service modifications
# sudo systemctl daemon-reload

# # 10. Enable and start Jenkins service
# sudo systemctl enable jenkins
# sudo systemctl restart jenkins

# # 11. Check if Jenkins is running
# sudo systemctl status jenkins

