---
- name: Install Jenkins, Terraform, and Nginx on Ubuntu
  hosts: jenkins
  become: yes
  tasks:
    # Update package list
    - name: Update APT packages
      apt:
        update_cache: yes

    # Install Java for Jenkins
    - name: Install Java (Jenkins dependency)
      apt:
        name: openjdk-17-jdk
        state: present

    # Install Jenkins
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    # Install Terraform
    - name: Install Terraform
      shell: |
        if ! command -v terraform &> /dev/null; then
          sudo apt install -y terraform
        fi

    # Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    # Deploy an HTML file (Simulated App)
    - name: Deploy application HTML page
      copy:
        content: "<h1>Welcome to My Nginx App on Jenkins Server</h1>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    # Set Environment Variables
    - name: Configure environment variables
      lineinfile:
        path: /etc/environment
        line: "APP_ENV=production"
        create: yes

    - name: Reload environment variables
      shell: source /etc/environment
